target-branch: main
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
helm-extra-args: --timeout 600s
check-version-increment: false
validate-maintainers: false
skip-missing-values: true
helm-extra-set-args: --set installCRDs=false