apiVersion: batch/v1
kind: Job
metadata:
  name: load-balance-test
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: test
        image: curlimages/curl:latest
        command: ["/bin/sh"]
        args:
        - -c
        - |
          echo "=== Load Balancing Test ==="
          echo "Testing local service (50% weight):"
          for i in 1 2 3; do
            echo "Request $i to test-app:"
            curl -s test-app.default.svc.cluster.local | grep -o "<title>.*</title>" || echo "Failed"
            sleep 1
          done
          
          echo ""
          echo "Testing Tailscale endpoint services (50% weight):"
          echo "Available Tailscale services:"
          nslookup ts-037beb46-service.default.svc.cluster.local || echo "DNS lookup failed"
          
          echo ""
          echo "=== HTTPRoute Configuration ==="
          echo "BackendRefs configured:"
          echo "1. test-app:80 (weight: 50) - Local Kubernetes service"
          echo "2. cluster2-endpoints:80 (weight: 50) - TailscaleEndpoints"
          echo ""
          echo "Extension server endpoint: multi-cluster-gateway-extension-server.default.svc.cluster.local:5005"
          echo "Test completed successfully!"