---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - patch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.tailscale.com
  resources:
  - tailscalegateways
  - tailscaleservice
  - tailscaletailnets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.tailscale.com
  resources:
  - tailscalegateways/finalizers
  - tailscaleservice/finalizers
  - tailscaletailnets/finalizers
  verbs:
  - update
- apiGroups:
  - gateway.tailscale.com
  resources:
  - tailscalegateways/status
  - tailscaleservice/status
  - tailscaletailnets/status
  verbs:
  - get
  - patch
  - update
