---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.envoyproxy.io
  - gateway.networking.k8s.io
  resources:
  - gateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.tailscale.com
  resources:
  - tailscaleendpoints
  - tailscalegateways
  - tailscaleroutepolicies
  - tailscaletailnets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.tailscale.com
  resources:
  - tailscaleendpoints/finalizers
  - tailscalegateways/finalizers
  - tailscaleroutepolicies/finalizers
  - tailscaletailnets/finalizers
  verbs:
  - update
- apiGroups:
  - gateway.tailscale.com
  resources:
  - tailscaleendpoints/status
  - tailscalegateways/status
  - tailscaleroutepolicies/status
  - tailscaletailnets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
