//go:build !ignore_autogenerated

/*
Copyright 2024 Tailscale Gateway Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/gateway-api/apis/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendSpec) DeepCopyInto(out *BackendSpec) {
	*out = *in
	if in.Weight != nil {
		in, out := &in.Weight, &out.Weight
		*out = new(int32)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendSpec.
func (in *BackendSpec) DeepCopy() *BackendSpec {
	if in == nil {
		return nil
	}
	out := new(BackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendStatus) DeepCopyInto(out *BackendStatus) {
	*out = *in
	if in.LastHealthCheck != nil {
		in, out := &in.LastHealthCheck, &out.LastHealthCheck
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendStatus.
func (in *BackendStatus) DeepCopy() *BackendStatus {
	if in == nil {
		return nil
	}
	out := new(BackendStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionSummary) DeepCopyInto(out *ConditionSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionSummary.
func (in *ConditionSummary) DeepCopy() *ConditionSummary {
	if in == nil {
		return nil
	}
	out := new(ConditionSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialStatus) DeepCopyInto(out *CredentialStatus) {
	*out = *in
	if in.LastValidated != nil {
		in, out := &in.LastValidated, &out.LastValidated
		*out = (*in).DeepCopy()
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TokenRefreshCount != nil {
		in, out := &in.TokenRefreshCount, &out.TokenRefreshCount
		*out = new(int64)
		**out = **in
	}
	if in.LastRefresh != nil {
		in, out := &in.LastRefresh, &out.LastRefresh
		*out = (*in).DeepCopy()
	}
	if in.ValidationErrors != nil {
		in, out := &in.ValidationErrors, &out.ValidationErrors
		*out = make([]DetailedError, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialStatus.
func (in *CredentialStatus) DeepCopy() *CredentialStatus {
	if in == nil {
		return nil
	}
	out := new(CredentialStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyStatus) DeepCopyInto(out *DependencyStatus) {
	*out = *in
	in.ResourceRef.DeepCopyInto(&out.ResourceRef)
	in.LastChecked.DeepCopyInto(&out.LastChecked)
	if in.ReadyConditions != nil {
		in, out := &in.ReadyConditions, &out.ReadyConditions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FailedConditions != nil {
		in, out := &in.FailedConditions, &out.FailedConditions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyStatus.
func (in *DependencyStatus) DeepCopy() *DependencyStatus {
	if in == nil {
		return nil
	}
	out := new(DependencyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DetailedError) DeepCopyInto(out *DetailedError) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
	if in.LastRetry != nil {
		in, out := &in.LastRetry, &out.LastRetry
		*out = (*in).DeepCopy()
	}
	if in.Context != nil {
		in, out := &in.Context, &out.Context
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.HTTPStatusCode != nil {
		in, out := &in.HTTPStatusCode, &out.HTTPStatusCode
		*out = new(int32)
		**out = **in
	}
	if in.ResourceRef != nil {
		in, out := &in.ResourceRef, &out.ResourceRef
		*out = new(LocalPolicyTargetReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DetailedError.
func (in *DetailedError) DeepCopy() *DetailedError {
	if in == nil {
		return nil
	}
	out := new(DetailedError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressRouteConfig) DeepCopyInto(out *EgressRouteConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressRouteConfig.
func (in *EgressRouteConfig) DeepCopy() *EgressRouteConfig {
	if in == nil {
		return nil
	}
	out := new(EgressRouteConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionServerConfig) DeepCopyInto(out *ExtensionServerConfig) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(ExtensionServerTLS)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionServerConfig.
func (in *ExtensionServerConfig) DeepCopy() *ExtensionServerConfig {
	if in == nil {
		return nil
	}
	out := new(ExtensionServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionServerStatus) DeepCopyInto(out *ExtensionServerStatus) {
	*out = *in
	if in.LastHookCall != nil {
		in, out := &in.LastHookCall, &out.LastHookCall
		*out = (*in).DeepCopy()
	}
	if in.HookCallMetrics != nil {
		in, out := &in.HookCallMetrics, &out.HookCallMetrics
		*out = new(HookCallMetrics)
		(*in).DeepCopyInto(*out)
	}
	if in.ReplicaStatus != nil {
		in, out := &in.ReplicaStatus, &out.ReplicaStatus
		*out = make([]ReplicaStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeploymentErrors != nil {
		in, out := &in.DeploymentErrors, &out.DeploymentErrors
		*out = make([]DetailedError, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionServerStatus.
func (in *ExtensionServerStatus) DeepCopy() *ExtensionServerStatus {
	if in == nil {
		return nil
	}
	out := new(ExtensionServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionServerTLS) DeepCopyInto(out *ExtensionServerTLS) {
	*out = *in
	if in.CertificateRef != nil {
		in, out := &in.CertificateRef, &out.CertificateRef
		*out = new(v1.SecretObjectReference)
		(*in).DeepCopyInto(*out)
	}
	if in.InsecureSkipVerify != nil {
		in, out := &in.InsecureSkipVerify, &out.InsecureSkipVerify
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionServerTLS.
func (in *ExtensionServerTLS) DeepCopy() *ExtensionServerTLS {
	if in == nil {
		return nil
	}
	out := new(ExtensionServerTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneratedRoutesStatus) DeepCopyInto(out *GeneratedRoutesStatus) {
	*out = *in
	if in.LastGeneration != nil {
		in, out := &in.LastGeneration, &out.LastGeneration
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneratedRoutesStatus.
func (in *GeneratedRoutesStatus) DeepCopy() *GeneratedRoutesStatus {
	if in == nil {
		return nil
	}
	out := new(GeneratedRoutesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HookCallMetrics) DeepCopyInto(out *HookCallMetrics) {
	*out = *in
	if in.AverageResponseTime != nil {
		in, out := &in.AverageResponseTime, &out.AverageResponseTime
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.LastCallDuration != nil {
		in, out := &in.LastCallDuration, &out.LastCallDuration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.HookTypeMetrics != nil {
		in, out := &in.HookTypeMetrics, &out.HookTypeMetrics
		*out = make(map[string]HookTypeMetric, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HookCallMetrics.
func (in *HookCallMetrics) DeepCopy() *HookCallMetrics {
	if in == nil {
		return nil
	}
	out := new(HookCallMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HookTypeMetric) DeepCopyInto(out *HookTypeMetric) {
	*out = *in
	if in.AverageResponseTime != nil {
		in, out := &in.AverageResponseTime, &out.AverageResponseTime
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HookTypeMetric.
func (in *HookTypeMetric) DeepCopy() *HookTypeMetric {
	if in == nil {
		return nil
	}
	out := new(HookTypeMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressRouteConfig) DeepCopyInto(out *IngressRouteConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressRouteConfig.
func (in *IngressRouteConfig) DeepCopy() *IngressRouteConfig {
	if in == nil {
		return nil
	}
	out := new(IngressRouteConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalPolicyTargetReference) DeepCopyInto(out *LocalPolicyTargetReference) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(v1.Namespace)
		**out = **in
	}
	if in.SectionName != nil {
		in, out := &in.SectionName, &out.SectionName
		*out = new(v1.SectionName)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalPolicyTargetReference.
func (in *LocalPolicyTargetReference) DeepCopy() *LocalPolicyTargetReference {
	if in == nil {
		return nil
	}
	out := new(LocalPolicyTargetReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationalMetrics) DeepCopyInto(out *OperationalMetrics) {
	*out = *in
	in.LastReconcileTime.DeepCopyInto(&out.LastReconcileTime)
	if in.ReconcileDuration != nil {
		in, out := &in.ReconcileDuration, &out.ReconcileDuration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.AverageReconcileTime != nil {
		in, out := &in.AverageReconcileTime, &out.AverageReconcileTime
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.ErrorRate != nil {
		in, out := &in.ErrorRate, &out.ErrorRate
		*out = new(string)
		**out = **in
	}
	if in.ThroughputPerHour != nil {
		in, out := &in.ThroughputPerHour, &out.ThroughputPerHour
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationalMetrics.
func (in *OperationalMetrics) DeepCopy() *OperationalMetrics {
	if in == nil {
		return nil
	}
	out := new(OperationalMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyDevice) DeepCopyInto(out *ProxyDevice) {
	*out = *in
	if in.LastSeen != nil {
		in, out := &in.LastSeen, &out.LastSeen
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyDevice.
func (in *ProxyDevice) DeepCopy() *ProxyDevice {
	if in == nil {
		return nil
	}
	out := new(ProxyDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxySpec) DeepCopyInto(out *ProxySpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxySpec.
func (in *ProxySpec) DeepCopy() *ProxySpec {
	if in == nil {
		return nil
	}
	out := new(ProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyStatus) DeepCopyInto(out *ProxyStatus) {
	*out = *in
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make([]ProxyDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyStatus.
func (in *ProxyStatus) DeepCopy() *ProxyStatus {
	if in == nil {
		return nil
	}
	out := new(ProxyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaStatus) DeepCopyInto(out *ReplicaStatus) {
	*out = *in
	if in.LastHealthCheck != nil {
		in, out := &in.LastHealthCheck, &out.LastHealthCheck
		*out = (*in).DeepCopy()
	}
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]DetailedError, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaStatus.
func (in *ReplicaStatus) DeepCopy() *ReplicaStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteGenerationConfig) DeepCopyInto(out *RouteGenerationConfig) {
	*out = *in
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(IngressRouteConfig)
		**out = **in
	}
	if in.Egress != nil {
		in, out := &in.Egress, &out.Egress
		*out = new(EgressRouteConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteGenerationConfig.
func (in *RouteGenerationConfig) DeepCopy() *RouteGenerationConfig {
	if in == nil {
		return nil
	}
	out := new(RouteGenerationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceDiscoveryConfig) DeepCopyInto(out *ServiceDiscoveryConfig) {
	*out = *in
	if in.SyncInterval != nil {
		in, out := &in.SyncInterval, &out.SyncInterval
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceDiscoveryConfig.
func (in *ServiceDiscoveryConfig) DeepCopy() *ServiceDiscoveryConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceDiscoveryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceDiscoveryDetails) DeepCopyInto(out *ServiceDiscoveryDetails) {
	*out = *in
	if in.LastDiscoveryDuration != nil {
		in, out := &in.LastDiscoveryDuration, &out.LastDiscoveryDuration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.DiscoveryErrors != nil {
		in, out := &in.DiscoveryErrors, &out.DiscoveryErrors
		*out = make([]DetailedError, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceDiscoveryDetails.
func (in *ServiceDiscoveryDetails) DeepCopy() *ServiceDiscoveryDetails {
	if in == nil {
		return nil
	}
	out := new(ServiceDiscoveryDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceInfo) DeepCopyInto(out *ServiceInfo) {
	*out = *in
	if in.VIPAddresses != nil {
		in, out := &in.VIPAddresses, &out.VIPAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
	if in.ConsumerClusters != nil {
		in, out := &in.ConsumerClusters, &out.ConsumerClusters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceInfo.
func (in *ServiceInfo) DeepCopy() *ServiceInfo {
	if in == nil {
		return nil
	}
	out := new(ServiceInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceStatus) DeepCopyInto(out *ServiceStatus) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastRegistration != nil {
		in, out := &in.LastRegistration, &out.LastRegistration
		*out = (*in).DeepCopy()
	}
	if in.ServiceTags != nil {
		in, out := &in.ServiceTags, &out.ServiceTags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RegistrationErrors != nil {
		in, out := &in.RegistrationErrors, &out.RegistrationErrors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceStatus.
func (in *ServiceStatus) DeepCopy() *ServiceStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailnetConfig) DeepCopyInto(out *TailnetConfig) {
	*out = *in
	in.TailscaleTailnetRef.DeepCopyInto(&out.TailscaleTailnetRef)
	if in.ServiceDiscovery != nil {
		in, out := &in.ServiceDiscovery, &out.ServiceDiscovery
		*out = new(ServiceDiscoveryConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RouteGeneration != nil {
		in, out := &in.RouteGeneration, &out.RouteGeneration
		*out = new(RouteGenerationConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailnetConfig.
func (in *TailnetConfig) DeepCopy() *TailnetConfig {
	if in == nil {
		return nil
	}
	out := new(TailnetConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailnetInfo) DeepCopyInto(out *TailnetInfo) {
	*out = *in
	if in.MagicDNSSuffix != nil {
		in, out := &in.MagicDNSSuffix, &out.MagicDNSSuffix
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.TailnetID != nil {
		in, out := &in.TailnetID, &out.TailnetID
		*out = new(string)
		**out = **in
	}
	if in.PlanType != nil {
		in, out := &in.PlanType, &out.PlanType
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailnetInfo.
func (in *TailnetInfo) DeepCopy() *TailnetInfo {
	if in == nil {
		return nil
	}
	out := new(TailnetInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailnetStatus) DeepCopyInto(out *TailnetStatus) {
	*out = *in
	if in.LastSync != nil {
		in, out := &in.LastSync, &out.LastSync
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.APIStatus != nil {
		in, out := &in.APIStatus, &out.APIStatus
		*out = new(TailscaleAPIStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceDiscoveryDetails != nil {
		in, out := &in.ServiceDiscoveryDetails, &out.ServiceDiscoveryDetails
		*out = new(ServiceDiscoveryDetails)
		(*in).DeepCopyInto(*out)
	}
	if in.LastError != nil {
		in, out := &in.LastError, &out.LastError
		*out = new(DetailedError)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailnetStatus.
func (in *TailnetStatus) DeepCopy() *TailnetStatus {
	if in == nil {
		return nil
	}
	out := new(TailnetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailscaleAPIStatus) DeepCopyInto(out *TailscaleAPIStatus) {
	*out = *in
	if in.LastSuccessfulCall != nil {
		in, out := &in.LastSuccessfulCall, &out.LastSuccessfulCall
		*out = (*in).DeepCopy()
	}
	if in.RateLimitRemaining != nil {
		in, out := &in.RateLimitRemaining, &out.RateLimitRemaining
		*out = new(int32)
		**out = **in
	}
	if in.RateLimitReset != nil {
		in, out := &in.RateLimitReset, &out.RateLimitReset
		*out = (*in).DeepCopy()
	}
	if in.LastError != nil {
		in, out := &in.LastError, &out.LastError
		*out = new(DetailedError)
		(*in).DeepCopyInto(*out)
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AverageResponseTime != nil {
		in, out := &in.AverageResponseTime, &out.AverageResponseTime
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailscaleAPIStatus.
func (in *TailscaleAPIStatus) DeepCopy() *TailscaleAPIStatus {
	if in == nil {
		return nil
	}
	out := new(TailscaleAPIStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailscaleGateway) DeepCopyInto(out *TailscaleGateway) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailscaleGateway.
func (in *TailscaleGateway) DeepCopy() *TailscaleGateway {
	if in == nil {
		return nil
	}
	out := new(TailscaleGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TailscaleGateway) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailscaleGatewayList) DeepCopyInto(out *TailscaleGatewayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TailscaleGateway, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailscaleGatewayList.
func (in *TailscaleGatewayList) DeepCopy() *TailscaleGatewayList {
	if in == nil {
		return nil
	}
	out := new(TailscaleGatewayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TailscaleGatewayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailscaleGatewaySpec) DeepCopyInto(out *TailscaleGatewaySpec) {
	*out = *in
	in.GatewayRef.DeepCopyInto(&out.GatewayRef)
	if in.Tailnets != nil {
		in, out := &in.Tailnets, &out.Tailnets
		*out = make([]TailnetConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtensionServer != nil {
		in, out := &in.ExtensionServer, &out.ExtensionServer
		*out = new(ExtensionServerConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailscaleGatewaySpec.
func (in *TailscaleGatewaySpec) DeepCopy() *TailscaleGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(TailscaleGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailscaleGatewayStatus) DeepCopyInto(out *TailscaleGatewayStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TailnetStatus != nil {
		in, out := &in.TailnetStatus, &out.TailnetStatus
		*out = make([]TailnetStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtensionServerStatus != nil {
		in, out := &in.ExtensionServerStatus, &out.ExtensionServerStatus
		*out = new(ExtensionServerStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.GeneratedRoutes != nil {
		in, out := &in.GeneratedRoutes, &out.GeneratedRoutes
		*out = new(GeneratedRoutesStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]ServiceInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RecentErrors != nil {
		in, out := &in.RecentErrors, &out.RecentErrors
		*out = make([]DetailedError, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OperationalMetrics != nil {
		in, out := &in.OperationalMetrics, &out.OperationalMetrics
		*out = new(OperationalMetrics)
		(*in).DeepCopyInto(*out)
	}
	if in.DependencyStatus != nil {
		in, out := &in.DependencyStatus, &out.DependencyStatus
		*out = make([]DependencyStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HTTPRouteRefs != nil {
		in, out := &in.HTTPRouteRefs, &out.HTTPRouteRefs
		*out = make([]LocalPolicyTargetReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailscaleGatewayStatus.
func (in *TailscaleGatewayStatus) DeepCopy() *TailscaleGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(TailscaleGatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailscaleService) DeepCopyInto(out *TailscaleService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailscaleService.
func (in *TailscaleService) DeepCopy() *TailscaleService {
	if in == nil {
		return nil
	}
	out := new(TailscaleService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TailscaleService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailscaleServiceList) DeepCopyInto(out *TailscaleServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TailscaleService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailscaleServiceList.
func (in *TailscaleServiceList) DeepCopy() *TailscaleServiceList {
	if in == nil {
		return nil
	}
	out := new(TailscaleServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TailscaleServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailscaleServiceSpec) DeepCopyInto(out *TailscaleServiceSpec) {
	*out = *in
	in.VIPService.DeepCopyInto(&out.VIPService)
	if in.Backends != nil {
		in, out := &in.Backends, &out.Backends
		*out = make([]BackendSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(ProxySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailscaleServiceSpec.
func (in *TailscaleServiceSpec) DeepCopy() *TailscaleServiceSpec {
	if in == nil {
		return nil
	}
	out := new(TailscaleServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailscaleServiceStatus) DeepCopyInto(out *TailscaleServiceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VIPServiceStatus != nil {
		in, out := &in.VIPServiceStatus, &out.VIPServiceStatus
		*out = new(ServiceStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ProxyStatus != nil {
		in, out := &in.ProxyStatus, &out.ProxyStatus
		*out = new(ProxyStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.BackendStatus != nil {
		in, out := &in.BackendStatus, &out.BackendStatus
		*out = make([]BackendStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastUpdate != nil {
		in, out := &in.LastUpdate, &out.LastUpdate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailscaleServiceStatus.
func (in *TailscaleServiceStatus) DeepCopy() *TailscaleServiceStatus {
	if in == nil {
		return nil
	}
	out := new(TailscaleServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailscaleTailnet) DeepCopyInto(out *TailscaleTailnet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailscaleTailnet.
func (in *TailscaleTailnet) DeepCopy() *TailscaleTailnet {
	if in == nil {
		return nil
	}
	out := new(TailscaleTailnet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TailscaleTailnet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailscaleTailnetList) DeepCopyInto(out *TailscaleTailnetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TailscaleTailnet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailscaleTailnetList.
func (in *TailscaleTailnetList) DeepCopy() *TailscaleTailnetList {
	if in == nil {
		return nil
	}
	out := new(TailscaleTailnetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TailscaleTailnetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailscaleTailnetSpec) DeepCopyInto(out *TailscaleTailnetSpec) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailscaleTailnetSpec.
func (in *TailscaleTailnetSpec) DeepCopy() *TailscaleTailnetSpec {
	if in == nil {
		return nil
	}
	out := new(TailscaleTailnetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailscaleTailnetStatus) DeepCopyInto(out *TailscaleTailnetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TailnetInfo != nil {
		in, out := &in.TailnetInfo, &out.TailnetInfo
		*out = new(TailnetInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.APIStatus != nil {
		in, out := &in.APIStatus, &out.APIStatus
		*out = new(TailscaleAPIStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.CredentialStatus != nil {
		in, out := &in.CredentialStatus, &out.CredentialStatus
		*out = new(CredentialStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.OperationalMetrics != nil {
		in, out := &in.OperationalMetrics, &out.OperationalMetrics
		*out = new(OperationalMetrics)
		(*in).DeepCopyInto(*out)
	}
	if in.RecentErrors != nil {
		in, out := &in.RecentErrors, &out.RecentErrors
		*out = make([]DetailedError, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeviceCount != nil {
		in, out := &in.DeviceCount, &out.DeviceCount
		*out = new(int32)
		**out = **in
	}
	if in.ConnectedDevices != nil {
		in, out := &in.ConnectedDevices, &out.ConnectedDevices
		*out = new(int32)
		**out = **in
	}
	if in.FeatureFlags != nil {
		in, out := &in.FeatureFlags, &out.FeatureFlags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailscaleTailnetStatus.
func (in *TailscaleTailnetStatus) DeepCopy() *TailscaleTailnetStatus {
	if in == nil {
		return nil
	}
	out := new(TailscaleTailnetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VIPServiceSpec) DeepCopyInto(out *VIPServiceSpec) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AutoApprove != nil {
		in, out := &in.AutoApprove, &out.AutoApprove
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VIPServiceSpec.
func (in *VIPServiceSpec) DeepCopy() *VIPServiceSpec {
	if in == nil {
		return nil
	}
	out := new(VIPServiceSpec)
	in.DeepCopyInto(out)
	return out
}
