apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale-gateway-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tailscale-gateway-operator
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["gateway.tailscale.com"]
  resources: ["tailscaletailnets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["gateway.tailscale.com"]
  resources: ["tailscaletailnets/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["gateway.tailscale.com"]
  resources: ["tailscaletailnets/finalizers"]
  verbs: ["update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tailscale-gateway-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tailscale-gateway-operator
subjects:
- kind: ServiceAccount
  name: tailscale-gateway-operator
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-gateway-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale-gateway-operator
  template:
    metadata:
      labels:
        app: tailscale-gateway-operator
    spec:
      serviceAccountName: tailscale-gateway-operator
      containers:
      - name: manager
        image: tailscale-gateway:test
        imagePullPolicy: Never
        args:
        - --log-level=debug
        ports:
        - containerPort: 8080
          name: metrics
        - containerPort: 8081
          name: health
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi