apiVersion: gateway.tailscale.com/v1alpha1
kind: TailscaleGateway
metadata:
  name: simple-test-gateway
  namespace: default
spec:
  # Reference to a hypothetical Envoy Gateway (doesn't need to exist for this test)
  gatewayRef:
    group: gateway.envoyproxy.io
    kind: Gateway
    name: test-gateway
    namespace: default

  # Configure a single tailnet
  tailnets:
  - name: test
    tailscaleTailnetRef:
      group: gateway.tailscale.com
      kind: TailscaleTailnet
      name: test-tailnet
    serviceDiscovery:
      enabled: false  # Disable service discovery to avoid API calls
    routeGeneration:
      ingress:
        hostPattern: "{service}.test.gateway.local"
        pathPrefix: "/"
        protocol: "HTTP"
      egress:
        hostPattern: "{service}.tailscale.local"
        pathPrefix: "/tailscale/{service}/"
        protocol: "HTTP"

  # Extension Server configuration (minimal for testing)
  extensionServer:
    image: "tailscale-gateway-extension:test"
    replicas: 1
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"