apiVersion: gateway.tailscale.com/v1alpha1
kind: TailscaleGateway
metadata:
  name: corp-gateway
  namespace: default
spec:
  # Reference to the Envoy Gateway this integrates with
  gatewayRef:
    name: eg-gateway
    namespace: envoy-gateway-system

  # Configure multiple tailnets
  tailnets:
  - name: corp
    tailscaleTailnetRef:
      name: corp-tailnet
    serviceDiscovery:
      enabled: true
      patterns:
      - "api-*"
      - "web-*"
      - "database-*"
      excludePatterns:
      - "proxy-*"
      - "gateway-*"
      syncInterval: "30s"
    routeGeneration:
      ingress:
        hostPattern: "{service}.corp.gateway.local"
        pathPrefix: "/"
        protocol: "HTTPS"
      egress:
        hostPattern: "{service}.tailscale.local"
        pathPrefix: "/tailscale/{service}/"
        protocol: "HTTP"

  - name: dev
    tailscaleTailnetRef:
      name: dev-tailnet
    serviceDiscovery:
      enabled: true
      patterns:
      - "dev-*"
      - "test-*"
      syncInterval: "60s"
    routeGeneration:
      ingress:
        hostPattern: "{service}.dev.gateway.local"
        pathPrefix: "/"
        protocol: "HTTP"
      egress:
        hostPattern: "{service}.dev.tailscale.local"
        pathPrefix: "/dev/{service}/"
        protocol: "HTTP"

  # Extension Server configuration
  extensionServer:
    image: "tailscale-gateway-extension:v1.0.0"
    replicas: 2
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    serviceAccountName: "tailscale-gateway-extension"