apiVersion: gateway.tailscale.com/v1alpha1
kind: TailscaleGateway
metadata:
  name: test-gateway
  namespace: default
spec:
  tailnetRef:
    name: test-tailnet
  gatewayRef:
    name: test-envoy-gateway
    namespace: default
  extensionServer:
    port: 5005
    tls:
      insecureSkipVerify: true  # For testing only
  routeDiscovery:
    enabled: true
    syncInterval: "30s"
    deviceSelector:
      tags:
        - tag:k8s
    routeFilters:
      - type: include
        cidrs:
          - "10.0.0.0/8"
          - "192.168.0.0/16"
      - type: exclude
        cidrs:
          - "10.96.0.0/12"  # Exclude k8s service network 