# This file is for teaching kustomize how to substitute name and namespace reference in CRD
nameReference:
- kind: Service
  version: v1
  fieldSpecs:
  - path: spec/conversion/webhook/clientConfig/service/name
    kind: CustomResourceDefinition