{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tailscale-gateway-operator.fullname" . }}-role
  labels:
    {{- include "tailscale-gateway-operator.labels" . | nindent 4 }}
rules:
# Core API resources
- apiGroups: [""]
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups: [""]
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups: [""]
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

# Apps API resources
- apiGroups: ["apps"]
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

# Tailscale Gateway CRDs
- apiGroups: ["gateway.tailscale.com"]
  resources:
  - tailscaletailnets
  - tailscalegateways
  - tailscaleroutepolicies
  - tailscaleendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups: ["gateway.tailscale.com"]
  resources:
  - tailscaletailnets/finalizers
  - tailscalegateways/finalizers
  - tailscaleroutepolicies/finalizers
  - tailscaleendpoints/finalizers
  verbs:
  - update
- apiGroups: ["gateway.tailscale.com"]
  resources:
  - tailscaletailnets/status
  - tailscalegateways/status
  - tailscaleroutepolicies/status
  - tailscaleendpoints/status
  verbs:
  - get
  - patch
  - update

# Gateway API resources
- apiGroups: ["gateway.networking.k8s.io"]
  resources:
  - gateways
  - httproutes
  - grpcroutes
  - tcproutes
  - tlsroutes
  - udproutes
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups: ["gateway.networking.k8s.io"]
  resources:
  - gateways/status
  - httproutes/status
  - grpcroutes/status
  - tcproutes/status
  - tlsroutes/status
  - udproutes/status
  verbs:
  - get
  - patch
  - update

# Coordination for leader election
- apiGroups: ["coordination.k8s.io"]
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
{{- end }} 