{{- if and .Values.extensionServer.enabled .Values.extensionServer.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tailscale-gateway-operator.fullname" . }}-extension-server
  namespace: {{ include "tailscale-gateway-operator.namespace" . }}
  labels:
    {{- include "tailscale-gateway-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: extension-server
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}