{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tailscale-gateway-operator.fullname" . }}-proxies-rolebinding
  namespace: {{ include "tailscale-gateway-operator.namespace" . }}
  labels:
    {{- include "tailscale-gateway-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "tailscale-gateway-operator.fullname" . }}-proxies-role
subjects:
- kind: ServiceAccount
  name: {{ include "tailscale-gateway-operator.serviceAccountName" . }}
  namespace: {{ include "tailscale-gateway-operator.namespace" . }}
{{- end }} 