name: Helm Chart Test

on:
  push:
    branches: [ "main" ]
    paths:
      - 'cmd/main/deploy/chart/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'cmd/main/deploy/chart/**'

jobs:
  chart-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: 'latest'

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.6.1

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Generate manifests and charts
      run: make generate-all

    - name: Run chart-testing (lint)
      run: ct lint --config .github/ct.yaml --chart-dirs cmd/main/deploy

    - name: Create kind cluster
      uses: helm/kind-action@v1.10.0

    - name: Run chart-testing (install)
      run: ct install --config .github/ct.yaml --chart-dirs cmd/main/deploy