name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Run tests
      run: make test

    - name: Run linter
      run: make lint

    - name: Generate manifests
      run: make generate-all

    - name: Verify no uncommitted changes
      run: |
        git add -A
        git diff --cached --exit-code || (echo "Generated files have uncommitted changes" && exit 1)


  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Build binary
      run: make build

    - name: Test Docker build
      run: make docker-build