name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Run tests
      run: go test ./... -v

    - name: Run linter
      run: make lint

    - name: Verify generated files are up-to-date
      run: |
        # Check if generated files exist and are up-to-date
        if [ ! -f "api/v1alpha1/zz_generated.deepcopy.go" ]; then
          echo "Error: Generated deepcopy file missing. Please run 'make generate' and commit."
          exit 1
        fi
        echo "Generated files verification passed ✓"


  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Build binary
      run: make build

    - name: Test Docker build
      run: make docker-build