name: Update Helm Chart for Main Branch

on:
  push:
    branches: [ "main" ]
    paths:
      - 'cmd/main/deploy/chart/**'
      - '.github/workflows/helm-main.yml'

env:
  REGISTRY: ghcr.io
  CHART_NAME: tailscale-gateway-operator

jobs:
  update-helm-latest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: 'latest'

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Generate manifests and charts
      run: make generate-all

    - name: Update chart for latest images
      run: |
        # Update values.yaml to use latest tags for main branch (both operator and extension server)
        sed -i 's/tag: ""/tag: "latest"/g' cmd/main/deploy/chart/values.yaml
        
        # Use 0.0.0 as chart version for main branch builds (like envoy-gateway)
        sed -i "s/version: .*/version: 0.0.0/" cmd/main/deploy/chart/Chart.yaml
        sed -i 's/appVersion: .*/appVersion: "latest"/' cmd/main/deploy/chart/Chart.yaml

    - name: Log in to GitHub Container Registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ${{ env.REGISTRY }} --username ${{ github.actor }} --password-stdin

    - name: Package and push Helm chart (latest)
      run: |
        # Package chart with 0.0.0 version for main branch
        helm package cmd/main/deploy/chart --version 0.0.0 --app-version latest
        
        # Push to OCI registry
        helm push ${CHART_NAME}-0.0.0.tgz oci://${{ env.REGISTRY }}/${{ github.repository_owner }}/charts
        
        echo "Published Helm chart: ${CHART_NAME}:0.0.0"