name: Update Manifests for Main Branch

on:
  push:
    branches: [ "main" ]
    paths:
      - 'cmd/main/deploy/manifests/**'
      - '.github/workflows/manifests-main.yml'

jobs:
  update-manifests-latest:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update manifests with latest tags
      run: |
        # Update the image tags in generated manifests to use latest
        sed -i "s|ghcr.io/rajsinghtech/tailscale-gateway.*:.*|ghcr.io/rajsinghtech/tailscale-gateway:latest|g" cmd/main/deploy/manifests/operator.yaml
        sed -i "s|ghcr.io/rajsinghtech/tailscale-gateway-extension-server:.*|ghcr.io/rajsinghtech/tailscale-gateway-extension-server:latest|g" cmd/main/deploy/manifests/operator.yaml

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        if git diff --quiet; then
          echo "No changes to commit"
        else
          git add cmd/main/deploy/manifests/operator.yaml
          git commit -m "Update manifests to use latest images for main branch

🤖 Generated with [Claude Code](https://claude.ai/code)

Co-Authored-By: Claude <noreply@anthropic.com>"
          git push
        fi