name: Verify Manifests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify-manifests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    
    - name: Verify generated files exist
      run: |
        # Check if all required generated files exist
        MISSING_FILES=""
        
        if [ ! -f "api/v1alpha1/zz_generated.deepcopy.go" ]; then
          MISSING_FILES="$MISSING_FILES api/v1alpha1/zz_generated.deepcopy.go"
        fi
        
        if [ ! -f "config/crd/bases/gateway.tailscale.com_tailscaleendpoints.yaml" ]; then
          MISSING_FILES="$MISSING_FILES config/crd/bases/gateway.tailscale.com_tailscaleendpoints.yaml"
        fi
        
        if [ ! -f "config/crd/bases/gateway.tailscale.com_tailscalegateways.yaml" ]; then
          MISSING_FILES="$MISSING_FILES config/crd/bases/gateway.tailscale.com_tailscalegateways.yaml"
        fi
        
        if [ -n "$MISSING_FILES" ]; then
          echo "Error: Missing generated files:"
          echo "$MISSING_FILES"
          echo "Please run 'make generate manifests generate-deploy' and commit the changes."
          exit 1
        fi
        
        echo "All required generated files are present ✓" 